import Navbar from '@/components/nav-utils/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="transition-all">
    <body className='container mx-auto'>
        <div className="flex min-h-screen flex-col justify-between">
          <div>
            <Navbar />
            <main className="mt-5">{children}</main>
          </div>
         
        </div>
    </body>
  </html>
  )
}
